name = "MissingLinks"
uuid = "472ee5c9-fceb-493a-8c64-09683b8345c2"
version = "0.2.2"
authors = ["Matt Bhagat-Conway <matt@indicatrix.org> and contributors"]

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
GDAL = "add2ef01-049f-52c4-9ee2-e494f65e021a"
GeoDataFrames = "62cb38b5-d8d2-4862-a48e-6a340996859f"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
LibSpatialIndex = "f19c2e90-9d16-5f2d-a2a7-af3fb29e4907"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
OpenStreetMapPBF = "32359c53-f983-4442-b913-a1664815e12e"
OverflowContexts = "649716ba-0eb1-4560-ace2-251185f55281"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"

[compat]
ArchGDAL = "0.10.8"
ArgParse = "1.2.0"
Artifacts = "1.9"
CSV = "0.10.15"
Compat = "4.16.0"
DataFrames = "1.7.0"
DataStructures = "0.18.22, 0.19"
Dates = "1.10"
DimensionalData = "0.29.18"
EzXML = "1.2.0"
GDAL = "1.9.0"
GeoDataFrames = "0.3.10"
GeoFormatTypes = "0.4.2"
GeoInterface = "1.3.8"
Graphs = "1.12.0"
LibGEOS = "0.9.2"
LibSpatialIndex = "0.2.2"
LinearAlgebra = "1.10"
Logging = "1.9"
MetaGraphsNext = "0.7.1, 0.8"
Mmap = "1.10"
OpenStreetMapPBF = "0.2.0, 0.3"
OverflowContexts = "0.2.7"
Pkg = "1.10"
ProgressMeter = "1.11.0"
Rasters = "0.14.0"
ThreadsX = "0.1.12"
julia = "1.10"
